settings:
  title: 'Status Page'
  url: 'https://cf-workers-status-page-production.dataserve.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: organizr-dataserve.top # unique identifier
    name: organizr.dataserve.top
    description: 'Organizr Landing Page' # default=empty
    url: 'https://organizr.dataserve.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: ombi-dataserve-top
    name: ombi.dataserve.top
    description: 'OMBI' # default=empty
    url: 'https://ombi.dataserve.top/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: plex-dataserve
    name: DataServe Plex
    description: 'Plex on DataServe' # default=empty
    url: 'http://wan.dataserve.top:32400/identity'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
